spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: ${DATABASE_URL}
#    username: ${DATABASE_USERNAME}
#    password: ${DATABASE_PASSWORD}
    url: jdbc:mariadb://lullaby.sldb.iwinv.net:3306/card_study
    username: card-study-prod
    password: card-study-prod!@#

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
