spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:./data/card-study?mode=MySQL;AUTO_SERVER=TRUE'
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


