spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:./data/card-study'
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: info

