spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mariadb://localhost:3312/card_study?useSSL=false&serverTimezone=UTC}
    username: ${DATABASE_USERNAME:card-study-app}
    password: ${DATABASE_PASSWORD:card-study-app}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
logging:
  level:
    root: info
