name: CI/CD with Gradle

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean test --stacktrace --parallel
      - name: Build with Gradle
        run: |
          ./gradlew bootJar --parallel
#      - name: Upload Jar
#        run: sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no ./build/libs/app.war ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}
      - name: Copy jar file to remote
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./build/libs/app.jar"
          target: ${{ secrets.DEPLOY_PATH }}
          strip_components: 1
